name: Build Tailwind CSS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**/*
      - package.json
      - tailwind.config.js
      - .github/workflows/tailwind-build.yaml
  pull_request:
    branches:
      - main
    paths:
      - src/**/*
      - package.json
      - tailwind.config.js

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      # with:
      #   node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build CSS
      run: npm run build
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        add-paths: |
          dist/*.css
        commit-message: 'New theme build'
